trigger logger event and and retry for git ops added
LF-Engineering/sync-data-sources pull request #87
Opened 2021-04-05 14:15 UTC by lfpratik

2021-04-06 10:14 UTC, lukaszgryglicki approved these changes
/lgtm please ping me when merged, because I will have to rebuild the base image.

2021-04-06 10:23 UTC, lukaszgryglicki requested changes
Remove the sensitive data from a public repo.

2021-04-06 10:23 UTC, lukaszgryglicki commented on docker-images/base/patch/perceval-trigger-error-event.py.diff
> ++        credentials=('dev.analytics.error.bot@gmail.com', 'Mobile@311!'),
Remove the sensitive data from a public PR.

2021-04-08 12:21 UTC, lfpratik commented on docker-images/base/patch/perceval-trigger-error-event.py.diff
> ++        credentials=('dev.analytics.error.bot@gmail.com', 'Mobile@311!'),
@lukaszgryglicki, I will do it. Let me know the environment variable I will pull those value from their.

2021-04-08 12:21 UTC, lfpratik commented on docker-images/base/patch/perceval-trigger-error-event.py.diff
> ++        credentials=('dev.analytics.error.bot@gmail.com', 'Mobile@311!'),
I will update the same for ALL PR

2021-04-08 13:56 UTC, lfpratik commented
@lukaszgryglicki, can you review this PR

2021-04-08 14:08 UTC, lukaszgryglicki approved these changes
/lgtm

2021-04-08 14:18 UTC, merged