Bugfix/da 3300
LF-Engineering/sync-data-sources pull request #88
Opened 2021-04-05 14:20 UTC by lfpratik

2021-04-06 10:19 UTC, lukaszgryglicki requested changes
Remove sensitive data from this PR.

2021-04-06 10:19 UTC, lukaszgryglicki commented on docker-images/base/patch/perceval-trigger-error-event.py.diff
> ++        credentials=('dev.analytics.error.bot@gmail.com', 'Mobile@311!'),
You know that SDS repo is public? A I can see password here.

2021-04-06 10:19 UTC, lukaszgryglicki commented on sources/cmd/syncdatasources/syncdatasources.go
> +	emailRegex        = regexp.MustCompile("^[a-zA-Z0-9.!#$%&'*+\\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$")
Is this related to anyti8ng from this PR?

2021-04-08 13:59 UTC, lfpratik commented on docker-images/base/patch/perceval-trigger-error-event.py.diff
> ++        credentials=('dev.analytics.error.bot@gmail.com', 'Mobile@311!'),
@lukaszgryglicki, Resolved

2021-04-08 13:59 UTC, lfpratik commented on sources/cmd/syncdatasources/syncdatasources.go
> +	emailRegex        = regexp.MustCompile("^[a-zA-Z0-9.!#$%&'*+\\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$")
I am not sure about this how it came

2021-04-08 14:18 UTC, closed without merging